import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'MagSafe Silicone Case',
    price: 49.00,
    category: 'Cases',
    image: 'https://picsum.photos/seed/case1/600/600',
    rating: 4.8,
    description: 'Silky, soft-touch finish of the silicone exterior feels great in your hand.',
    isNew: true,
  },
  {
    id: '2',
    name: '30W USB-C Power Adapter',
    price: 29.00,
    category: 'Chargers',
    image: 'https://picsum.photos/seed/charger1/600/600',
    rating: 4.9,
    description: 'Fast, efficient charging at home, in the office, or on the go.',
  },
  {
    id: '3',
    name: 'Wireless Noise Cancelling Buds',
    price: 159.00,
    category: 'Audio',
    image: 'https://picsum.photos/seed/audio1/600/600',
    rating: 4.7,
    description: 'Immersive sound with active noise cancellation and transparency mode.',
    isNew: true,
  },
  {
    id: '4',
    name: 'Ultra-Clear Screen Protector',
    price: 19.00,
    category: 'Protection',
    image: 'https://picsum.photos/seed/glass1/600/600',
    rating: 4.5,
    description: 'High-quality tempered glass with 9H hardness for ultimate protection.',
  },
  {
    id: '5',
    name: 'Leather Wallet with MagSafe',
    price: 59.00,
    category: 'Cases',
    image: 'https://picsum.photos/seed/wallet1/600/600',
    rating: 4.6,
    description: 'Crafted from specially tanned and finished European leather.',
  },
  {
    id: '6',
    name: 'Multi-Device Charging Station',
    price: 89.00,
    category: 'Chargers',
    image: 'https://picsum.photos/seed/station1/600/600',
    rating: 4.8,
    description: 'Charge your phone, watch, and buds all in one elegant place.',
  },
];
